export const th = { textAlign: 'left', padding: 10, borderBottom: '1px solid #eef2f7', fontSize: 13, color: '#475569', background: '#f9fbfd' }
export const td = { padding: 10, borderBottom: '1px solid #f2f5fa', fontSize: 14 }
export const ctrl = { padding: '8px 10px', borderRadius: 8, border: '1px solid #d1d9e6' }
export const btn = { marginLeft: 6, padding: '8px 10px', borderRadius: 8, border: '1px solid #d1d9e6', background: '#fff', cursor: 'pointer' }
export const btnPrimary = { padding: '10px 14px', borderRadius: 10, border: '1px solid #1f6feb', background: '#1f6feb', color: '#fff', fontWeight: 600 }
export const btnSuccess = { padding: '8px 12px', borderRadius: 8, border: '1px solid #16a34a', background: '#16a34a', color: '#fff', fontWeight: 600, cursor: 'pointer' }
export const btnDanger = { padding: '8px 12px', borderRadius: 8, border: '1px solid #dc2626', background: '#dc2626', color: '#fff', fontWeight: 600, cursor: 'pointer' }
export const tableWrap = { overflow: 'auto', border: '1px solid #e6eaf0', borderRadius: 12 }
export const table = { width: '100%', borderCollapse: 'collapse' }
export const metaText = { color: '#64748b', fontSize: 12 }
export const errorText = { color: '#e11d48' }
export const pageContainer = { padding: 20, maxWidth: 1200, margin: '0 auto' }
export const pageTitle = { marginTop: 0 }